# Generated by Django 3.2.12 on 2022-02-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('begin', models.DateField(db_index=True, verbose_name='holiday begin date')),
                ('end', models.DateField(db_index=True, verbose_name='holiday end date')),
                ('description', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='holidays.country')),
            ],
            options={
                'verbose_name': 'holiday',
                'verbose_name_plural': 'holidays',
            },
        ),
    ]
